name: firebase_messaging_devtool
version: 0.1.0
issueTracker: https://github.com/FredrikBorgstrom/firebase_messaging_devtool/issues
materialIconCodePoint: '0xe3e0' # A basic message icon, you can change this 